# Generated by Django 5.0.7 on 2024-07-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_author', '0002_rename_author_book_author_kkk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_kkk',
            new_name='author',
        ),
    ]
